language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-29.0.2
    - android-29
    - extra-android-m2repository

before_install:
  - chmod +x gradlew

after_script:
  - bash ./telegram_notification.sh

script:
  - ./gradlew build

notifications:
  email:
    recipients:
    - rifqi.fadhlillah@gmail.com
    on_success: never
    on_failure: always